feat:Userモデルを実装した
ok-os-job-change-team/tetsuya-twitter-clone-bootcamp pull request #21
Opened 2024-04-22 11:52 UTC by kawabuchi-tetsuya

## 今回対応した issue

- closes #4 

## やったこと

- `schema.rb` を記述し、 `rake db:schema:load` を実行した
- `seeds.rb` を記述し、 `rake db:seed RAIL_ENV=TEST` を実行した
- `user_spec.rb` にuserのemailとpasswordがそれぞれnilとなるときのテストを記述し、実行した

## 残りの作業

- なし

## できるようになること（ユーザ目線）

- なし

## できなくなること（ユーザ目線）

- なし

## その他

- なし

## 動作確認

-  `rake db:seed RAIL_ENV=TEST` 後に `SELECT * FROM users;` を実行した結果
![Screenshot 2024-04-22 20 37 56](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/assets/95535099/6c437674-22b5-45b6-bcce-dfd950283256)
- RSpec実行結果
![Screenshot 2024-04-22 20 38 30](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/assets/95535099/98d01021-c7ab-4888-a5ff-a20a17df45ea)

2024-04-23 03:12 UTC, ochi-sho-private-study reviewed
@kawabuchi-tetsuya 
コメントした！

あと、
`rake db:schema:load`を実行する代わりに、
ridgepoleを用いてマイグレーションを行うmigrationを行なってくれるrakeタスクを作成して、
そのrakeタスク実行時に以下のコードも実行するようにしたらいいと思うよ！
```ruby
Rake::Task['db:schema:dump'].invoke
```

Ref: https://qiita.com/lhside/items/0dcad79d9b801e34bc7c

2024-04-23 03:12 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +      user.valid?
ここのテストはひとまとめにできると思う。
また、こちらの方がexampleブロックが一個減るので、
`build(:user)`の実行回数が1回減る。
したがって、テストの実行速度やメモリの消費が少なく済みます。

```
it do
  expect(user.valid?).to be true
  expect(user.errors.full_messages).to eq([])
end
```

2024-04-23 03:12 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +    end
エラーメッセージ(`user.errors.full_messages`)もテストしてみよう。

2024-04-23 03:12 UTC, ochi-sho-private-study commented on db/seeds.rb
> +# coding: utf-8
このコメントは必要かな？
rubyはデフォルトで文字コードはUTF-8だったはず。

2024-04-23 03:12 UTC, ochi-sho-private-study commented on db/schema.rb
> +  create_table 'users', id: { type: :integer, comment: 'ユーザーID', unsigned: true, default: nil }, charset: 'utf8mb4', collation: 'utf8mb4_bin', comment: 'ユーザー', force: :cascade do |t|
PKとなるIDは、自動で付与されると思うので、以下の記述でいいと思う！


```suggestion
  create_table 'users', charset: 'utf8mb4', collation: 'utf8mb4_bin', comment: 'ユーザー', force: :cascade do |t|
```

2024-04-23 03:20 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +    example 'errorsに「email列が空であるエラー」が格納される' do
改行しよう

```suggestion
    let(:user) {build(:user, email:nil)}

    example 'errorsに「email列が空であるエラー」が格納される' do
```

2024-04-23 03:20 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +    example 'errorsに「password列が空であるエラー」が格納される' do
改行しよう

```suggestion
    let(:user) {build(:user, password:nil)}

    example 'errorsに「password列が空であるエラー」が格納される' do
```

2024-04-23 05:10 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +    example 'errorsに「password列が空であるエラー」が格納される' do
[f400c29](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/f400c293e24e606c4dda3ca455b41dc64c1ad4a1)
で対応

2024-04-23 05:11 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +    example 'errorsに「email列が空であるエラー」が格納される' do
[f400c29](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/f400c293e24e606c4dda3ca455b41dc64c1ad4a1)
で対応

2024-04-23 05:11 UTC, kawabuchi-tetsuya commented on db/schema.rb
> +  create_table 'users', id: { type: :integer, comment: 'ユーザーID', unsigned: true, default: nil }, charset: 'utf8mb4', collation: 'utf8mb4_bin', comment: 'ユーザー', force: :cascade do |t|
[f400c29](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/f400c293e24e606c4dda3ca455b41dc64c1ad4a1)
で対応

2024-04-23 05:11 UTC, kawabuchi-tetsuya commented on db/seeds.rb
> +User.create(:id => 1, :email => 'user1@example.com', :password => 'p@ssw0rd')
[f400c29](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/f400c293e24e606c4dda3ca455b41dc64c1ad4a1)
で対応

2024-04-23 05:11 UTC, kawabuchi-tetsuya commented on db/seeds.rb
> +# coding: utf-8
[f400c29](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/f400c293e24e606c4dda3ca455b41dc64c1ad4a1)
で対応

2024-04-23 05:11 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +    end
[f400c29](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/f400c293e24e606c4dda3ca455b41dc64c1ad4a1)
で対応

2024-04-23 05:11 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +      user.valid?
[f400c29](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/f400c293e24e606c4dda3ca455b41dc64c1ad4a1)
で対応

2024-04-23 05:12 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +    example 'userが有効である' do
[f400c29](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/f400c293e24e606c4dda3ca455b41dc64c1ad4a1)
で対応

2024-04-23 05:14 UTC, kawabuchi-tetsuya commented
@ochi-sho-private-study 
[f400c29](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/f400c293e24e606c4dda3ca455b41dc64c1ad4a1)
修正しました
- RSpec実行結果
![Screenshot 2024-04-22 20 38 30](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/assets/95535099/a7f09a2e-28a0-4a77-ba8d-b55d8d00a610)
- usersテーブル内容
![Screenshot 2024-04-23 13 53 16](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/assets/95535099/be99ac0e-8dc6-46f3-8fb5-a5b2adb2ac5f)

2024-04-24 03:20 UTC, ochi-sho-private-study approved these changes
@kawabuchi-tetsuya 
コメントしたけどLGTM!

2024-04-24 03:20 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +  context 'emailとpasswordがそれぞれ有効な値であるとき' do
IMO/Idiomatic

以下のように、describeを書いた方が良いかな！
（Userモデルには、validation以外にも他のメソッドもテストする時がきそうなため。）

```ruby
RSpec.describe User, type: :model do
  describe '#validation' do
    context 'emailとpasswordがそれぞれ有効な値であるとき' do
    end
  end
end
```

2024-04-24 03:23 UTC, ochi-sho-private-study commented on db/schema/user.schema
>  end
Idiomatic

created_atとupdated_atカラムも生やそう
`t.timestamp`を実行すると生やせたと思う。

2024-04-24 03:25 UTC, ochi-sho-private-study requested changes
やっぱりapprove取り消しで！

2024-04-24 03:25 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +      expect(user.errors.full_messages).to eq([])
`aggregate_failures`メソッドを使おう！
なんでかはわかるかな？

Ref: https://blog.solunita.net/posts/easy-to-write-rspec-by-aggregate-failures-and-request-describer/

2024-04-25 06:15 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +      expect(user.errors.full_messages).to eq([])
[646d4bf](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/646d4bf53c4ae5f00fc2e13c36ee2463774ae95e) で対応しました。

2024-04-25 06:15 UTC, kawabuchi-tetsuya commented on db/schema/user.schema
>  end
[646d4bf](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/646d4bf53c4ae5f00fc2e13c36ee2463774ae95e) で対応しました。

2024-04-25 06:15 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +  context 'emailとpasswordがそれぞれ有効な値であるとき' do
[646d4bf](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/646d4bf53c4ae5f00fc2e13c36ee2463774ae95e) で対応しました。

2024-04-25 06:18 UTC, kawabuchi-tetsuya commented
@ochi-sho-private-study 
修正しました
[646d4bf](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/646d4bf53c4ae5f00fc2e13c36ee2463774ae95e)
- RSpec実行結果
![Screenshot 2024-04-25 15 09 36](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/assets/95535099/7dfed59f-1391-4c9c-b992-9a1c6d633ed8)
- rails_test.users内容
![Screenshot 2024-04-25 15 07 35](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/assets/95535099/472e064c-f79e-46a7-85c8-2858dc03d998)

2024-04-25 14:07 UTC, ochi-sho-private-study reviewed
@kawabuchi-tetsuya 
コメントした！

2024-04-25 14:07 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +      let(:user) {build(:user, password:nil)}
Nits/Idiomatic

```suggestion
      let(:user) { build(:user, password: nil) }
```

2024-04-25 14:07 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +      let(:user) {build(:user, email:nil)}
Nits/Idiomatic

```suggestion
      let(:user) { build(:user, email: nil) }
```

2024-04-25 14:07 UTC, ochi-sho-private-study commented on db/schema/user.schema
> +  t.timestamp 'updated_at', null: false, comment: '更新日時'
Simple

`t.timestamp`だけで良いと思う！

Ref: https://blog.wyrd.co.jp/2023/04/10/timestamps%E3%83%9E%E3%82%AF%E3%83%AD%E3%81%A8%E3%81%AF%E4%BD%95%E8%80%85%E3%81%AA%E3%81%AE%E3%81%8B%EF%BC%9F/
```suggestion
  t.timestamp
```

2024-04-25 14:07 UTC, ochi-sho-private-study commented on db/schema/user.schema
> +# ridgepole導入とridgepole.rakeにより、コマンドrake ridgepole:apply testでschema.rbとrails_test.usersに反映される
ここに書くのではなく、README.mdに書いた方がいいと思うよ！

> rails_test.usersに反映される

これは、test環境のDBにmigrationが反映される、と言うことを書きたかったのかね？

2024-04-25 14:07 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +      expect(user.errors.full_messages).to eq([])
> なんでかはわかるかな？

このコメントに関して返信が欲しいです。

2024-04-26 04:36 UTC, kawabuchi-tetsuya commented on db/schema/user.schema
> +# ridgepole導入とridgepole.rakeにより、コマンドrake ridgepole:apply testでschema.rbとrails_test.usersに反映される
[dd821fb](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/dd821fba1c78e4fd85e9d7e3e3f53f03bd7dd318) で対応しました。
質問内容については、その見解で合ってる。

2024-04-26 04:38 UTC, kawabuchi-tetsuya commented on db/schema/user.schema
> +  t.timestamp 'updated_at', null: false, comment: '更新日時'
[dd821fb](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/dd821fba1c78e4fd85e9d7e3e3f53f03bd7dd318) で対応しました。
リンク先見ても検索しても、`timestamps`がヒットしたけど、s付きで合ってる？

2024-04-26 04:38 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +      let(:user) {build(:user, email:nil)}
[dd821fb](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/dd821fba1c78e4fd85e9d7e3e3f53f03bd7dd318) で対応しました。

2024-04-26 04:38 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +      let(:user) {build(:user, password:nil)}
[dd821fb](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/dd821fba1c78e4fd85e9d7e3e3f53f03bd7dd318) で対応しました。

2024-04-26 04:46 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +      expect(user.errors.full_messages).to eq([])
一つのテストケースに対して複数の `expect` を書いているから。
`aggregate_failures` メソッドなしだと、複数項目でパスしない状態であっても、テスト実行時に最初にパスしなかった項目しかわからない。

2024-04-26 04:46 UTC, kawabuchi-tetsuya commented
@ochi-sho-private-study 
修正しました。
[dd821fb](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/dd821fba1c78e4fd85e9d7e3e3f53f03bd7dd318)

2024-04-26 04:50 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +      expect(user.errors.full_messages).to eq([])
正解！

2024-04-26 04:52 UTC, ochi-sho-private-study approved these changes
@kawabuchi-tetsuya 
コメントしたけど、LGTM!

2024-04-26 04:52 UTC, ochi-sho-private-study commented on spec/models/user_spec.rb
> +    context 'emailとpasswordがそれぞれ有効な値であるとき' do
IMO

emailとpassword以外のカラムが増えることもありえるし、
そもそも現時点でもcreated_atといった属性も存在しているので、
「属性が全て有効な値であるとき」のほうが良いかなと思った！

2024-04-26 04:54 UTC, ochi-sho-private-study commented on db/schema/user.schema
> +  t.timestamp 'updated_at', null: false, comment: '更新日時'
ごめん、.timestampsだったわ

https://railsguides.jp/active_record_migrations.html#%E3%83%9E%E3%82%A4%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E6%A6%82%E8%A6%81

2024-04-26 05:23 UTC, kawabuchi-tetsuya commented on spec/models/user_spec.rb
> +    context 'emailとpasswordがそれぞれ有効な値であるとき' do
[b54656c](https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/21/commits/b54656c6f9b9e37a81d51e188d23613a5fd6f49d) で対応しました。

2024-04-26 05:24 UTC, merged