#72 フォロー機能を追加する
ok-os-job-change-team/tetsuya-twitter-clone-bootcamp pull request #74
Opened 2024-07-13 03:50 UTC by kawabuchi-tetsuya

## 今回対応した issue

- closes #72 
## やったこと

- ユーザーフォロー機能を追加した
  - 中間テーブル (relationships) の実装
  - モデル (Relationship) の実装
  - コントローラー (Relationships) の実装

## 残りの作業

- なし

## できるようになること（ユーザ目線）

- ユーザーが、自身以外のユーザーをフォローできる
- ユーザーが、自身以外のユーザーからフォローされうる

## できなくなること（ユーザ目線）

- なし

## その他

- なし

## 動作確認

https://github.com/user-attachments/assets/4210514f-80a9-4469-a8d1-affde456ada2

2024-07-20 06:37 UTC, kawabuchi-tetsuya commented
https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/74/commits/ce47a6e47b79ef09f73983df6ba26b92991c7acf
N+1問題を解消しました。

## 動作確認
https://github.com/user-attachments/assets/6e865058-40cb-4875-98dd-a636f981a1f8

## ER図
```mermaid
erDiagram

%% 1:0or多
USERS ||--o{ POSTS : "has many / belongs to"
USERS ||--o{ FAVORITES : "has many / belongs to"
POSTS ||--o{ FAVORITES : "has many / belongs to"

 USERS {
  bigint id PK
  string email
  string password_digest
  datetime created_at
  datetime updated_at
}

POSTS {
  bigint id PK
  bigint user_id FK
  string title
  string content
  datetime created_at
  datetime updated_at
}

FAVORITES {
  bigint id PK
  bigint post_id FK
  bigint user_id FK
  datetime created_at
  datetime updated_at
}
```
### ユーザーフォロー機能
```mermaid
erDiagram

%% ユーザーフォロー機能
"USERS (FOLLOWERS)" ||--o{ RELATIONSHIPS : "has many / belongs to"
"USERS (FOLLOWEES)" ||--o{ RELATIONSHIPS : "has many / belongs to"

"USERS (FOLLOWERS)" {
  bigint id PK
  string email
  string password_digest
  datetime created_at
  datetime updated_at
}

"USERS (FOLLOWEES)" {
  bigint id PK
  string email
  string password_digest
  datetime created_at
  datetime updated_at
}

RELATIONSHIPS {
  bigint id PK
  bigint follower_id FK
  bigint followee_id FK
  datetime created_at
  datetime updated_at
}
```

2024-07-21 13:28 UTC, ochi-sho-private-study reviewed
@kawabuchi-tetsuya 
コメントしやした

2024-07-24 01:35 UTC, kawabuchi-tetsuya commented
@ochi-sho-private-study 
変更しました。
https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/74/commits/3cc1533d92c6a7377ab3ac71b80e157e25f5539b

2024-07-24 01:36 UTC, kawabuchi-tetsuya commented on app/models/user.rb
> +                                  }, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy,
変更しました。
https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/74/commits/3cc1533d92c6a7377ab3ac71b80e157e25f5539b

2024-07-24 01:36 UTC, kawabuchi-tetsuya commented on app/models/user.rb
> +  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followee_id', dependent: :destroy,
変更しました。
https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/74/commits/3cc1533d92c6a7377ab3ac71b80e157e25f5539b

2024-07-24 01:36 UTC, kawabuchi-tetsuya commented on Gemfile
> +  gem 'bullet'
一旦削除しました。
https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/74/commits/3cc1533d92c6a7377ab3ac71b80e157e25f5539b

2024-07-24 09:20 UTC, kawabuchi-tetsuya commented
@ochi-sho-private-study 
`followee?` メソッドを `active_relationship.rb`から削除しました。
https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/74/commits/b1d7d5e60f42499933337af1d02a151a3d21131c

2024-07-27 02:59 UTC, ochi-sho-private-study approved these changes
~~LGTM!~~

やっぱりもうちょっとちゃんとレビューします

2024-07-27 02:59 UTC, ochi-sho-private-study commented on app/models/user.rb
> +  end
`user.follow`・`user.unfollow`が直感的に分かりやすくなってていいね！ 👍

2024-07-27 03:00 UTC, ochi-sho-private-study requested changes
一旦消す

2024-07-27 03:03 UTC, ochi-sho-private-study commented on app/controllers/relationships_controller.rb
> +  end
User::FolloweesControllerを作った方が慣習的だな。

2024-07-27 03:03 UTC, ochi-sho-private-study commented on app/controllers/relationships_controller.rb
> +  # GET /users/:user_id/followers
`User::FollowersController`を作った方が慣習的だな。
あんまりindex/create/update/edit/new/destroyアクションから外れたメソッドを生やしたくない。

2024-07-31 14:58 UTC, ochi-sho-private-study reviewed
@kawabuchi-tetsuya 
一旦気になったところコメントした！

2024-07-31 14:58 UTC, ochi-sho-private-study commented on app/controllers/relationships_controller.rb
> +    if current_user.follow(user)
simple

一時変数に入れる必要がなさそう。
```suggestion
    if current_user.follow(User.find(params[:user_id]))
```

2024-08-02 06:52 UTC, kawabuchi-tetsuya commented on app/controllers/relationships_controller.rb
> +  end
対応しました。
https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/74/commits/c53016707e6fd8d3f29bdc82ffac8d8fd1c3f2a4

2024-08-02 06:52 UTC, kawabuchi-tetsuya commented on app/controllers/relationships_controller.rb
> +  # GET /users/:user_id/followers
対応しました。
https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/74/commits/c53016707e6fd8d3f29bdc82ffac8d8fd1c3f2a4

2024-08-02 06:52 UTC, kawabuchi-tetsuya commented on app/controllers/relationships_controller.rb
> +    if current_user.follow(user)
対応しました。
https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/74/commits/c53016707e6fd8d3f29bdc82ffac8d8fd1c3f2a4

2024-08-02 06:53 UTC, kawabuchi-tetsuya commented
@ochi-sho-private-study 
ひとまず対応しました。
https://github.com/ok-os-job-change-team/tetsuya-twitter-clone-bootcamp/pull/74/commits/c53016707e6fd8d3f29bdc82ffac8d8fd1c3f2a4

2024-08-04 10:40 UTC, ochi-sho-private-study reviewed
@kawabuchi-tetsuya 
コメントしたで

2024-08-04 10:40 UTC, ochi-sho-private-study commented on spec/models/user/user_relationship_extension_spec.rb
> +  end
この記述ってなんで必要なんだっけ？

2024-08-04 10:40 UTC, ochi-sho-private-study commented on spec/models/user/user_relationship_extension_spec.rb
> +  let!(:active_relationship2) { ActiveRelationship.create(follower: user, followee: followee2) }
以下のようにすると、letが減らせると思った！
（letは極力減らすべきという考えが慣習的なので）

```suggestion
  let!(:active_relationships) do
    {
      1 => ActiveRelationship.create(follower: user, followee: followee1),
      2 => ActiveRelationship.create(follower: user, followee: followee2)
    }
  end
```

2024-08-04 10:40 UTC, ochi-sho-private-study commented on spec/factories/relationships.rb
- ActiveRelationship
- PassiveRelationship

のfactoryも作成するとテストをより簡潔に書けると思った！

2024-08-04 10:40 UTC, ochi-sho-private-study commented on spec/models/relationship_spec.rb
> +  describe '#associations' do
ブロック間は改行しよか
```suggestion
  end

  describe '#associations' do
```

2024-08-04 10:40 UTC, ochi-sho-private-study commented on app/models/relationship.rb
> +  belongs_to :followee, class_name: 'User', inverse_of: :passive_relationships
Relationshipクラスから直接これらを呼び出すことは無くなったはずなので、
ここの関連は不要になったと思う！

2024-08-10 06:28 UTC, ochi-sho-private-study approved these changes
@kawabuchi-tetsuya 
LGTM! ❤️ 
他のコメントは別issueでリファクタリングとしてやろう！

2024-08-10 06:30 UTC, merged

2024-08-10 06:31 UTC, ochi-sho-private-study commented on app/models/relationship.rb
> +  belongs_to :followee, class_name: 'User', inverse_of: :passive_relationships
やっぱ必要かも。
以下のようにするのがいいかも。

```ruby
class Relationship
  def resolve(status)
    case status
    when :active
      becomes(ActiveRelationship)
    when :passive
      becomes(PassiveRelationship)
    end
  end
end
```